#!/bin/sh

echo "Initial configuration..."
./configure
source ./environment

./setup.${fw_cfg_distro}

echo "Reconfiguring..."
./configure
source ./environment

#$GNUMAKE configure
${fw_cfg_make} install
